Default: &defaults
  user: yuplanner
  password: yuplanner
  host: localhost
  database: yuplanner
  port: 5432
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yuplanner_test
  <<: *defaults

Staging:
  database: yuplanner_staging
  poolsize: 100
  <<: *defaults

Production:
  user: ejgcawkqyedgrv
  password: f1YpK4EjX2QLcxvVLwdpbQdge6
  host: ec2-54-243-250-125.compute-1.amazonaws.com
  port: 5432
  database: d45fsql4989lft
  poolsize: 100
  <<: *defaults
