Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:4567"
  #approot: "http://192.168.1.80:4567"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://yuplanner.herokuapp.com"
  <<: *defaults
